### ISSUE TITLE
Add query expansion

### ISSUE THREAD

**Issue by acheng96** [Jma353/cu-there#25]

**Comment by acheng96** [comment]
TA comments: "If the user enters "apple festival", show some possible suggestions on expanding the query such as "outdoor apple festival" which is learned from the past events in the dataset."
"

**Comment by Jma353** [comment]
We start suggesting words via Lev now, but adding thesaurus generation to improve our ability to associate words like "panel" with "talk" and "discussion" based on various features that I'm working on determining now.

**Comment by acheng96** [comment]
Maybe we can display "query expansion" words under the search bar or in the search suggestions list so people can just click on them

**Comment by acheng96** [comment]
Addressed in 6343bf0
